"""empty message

Revision ID: 635d6e3ca6ad
Revises: 822b515cf61c
Create Date: 2024-08-23 21:39:10.444962

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '635d6e3ca6ad'
down_revision: Union[str, None] = '822b515cf61c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contactentrymodel', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contactentrymodel', schema=None) as batch_op:
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
